### ISSUE TITLE
Occasional error when releasing after charging up a lot

### ISSUE THREAD

**Issue by jacius** [shawn42/free-radicals#1]
Sometimes I get the following error if I charge up a lot and then let go (the error occurs as soon as I let go). I can trigger it pretty reliably on level 3 by charging up the huge all the way, moving the mouse cursor to the smallest atom, and then releasing. It can also occur on other levels.

```
./src/../config/../src/atom.rb:185:in `discharge': undefined method `x' for nil:NilClass (NoMethodError)
    from ./src/../config/../src/atom.rb:87:in `setup'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:71:in `call'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:71:in `main_loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:70:in `each'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:70:in `main_loop'
    from /usr/lib/ruby/site_ruby/1.8/rubygame/queue.rb:110:in `_old_each'
    from /usr/lib/ruby/site_ruby/1.8/rubygame/queue.rb:110:in `each'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:50:in `main_loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:48:in `loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:48:in `main_loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:47:in `catch'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/input_manager.rb:47:in `main_loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/gamebox_application.rb:49:in `main_loop'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/gamebox_application.rb:63:in `start'
    from /usr/lib/ruby/gems/1.8/gems/gamebox-0.0.4/lib/gamebox/gamebox_application.rb:22:in `run'
    from src/app.rb:7
```

**Comment by shawn42** [comment]
Nice bug, nice write up.  It is fixed in git now.  It had to do with finding the nears electron to where the mouse was released.

**Comment by shawn42** [comment]
fixed.
